version: 2

defaults: &defaults
  working_directory: ~/apto-ui
  docker:
    - image: circleci/node:8-browsers

jobs:
  continuous-integration:
    <<: *defaults
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn install
      - run: yarn lint
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn test:headless
      - add_ssh_keys:
          fingerprints:
              - "a8:26:24:e0:0a:8e:bb:6c:5b:81:4e:df:c5:7d:51:5d"
      - run: >
          if [ "$CIRCLE_BRANCH" == "master" ]; then
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
            npm run release
          fi

workflows:
  version: 2
  branches:
    jobs:
      - continuous-integration:
          filters:
            branches:
              ignore: master
  master:
    jobs:
      - continuous-integration:
          filters:
            branches:
              only: master
