version: 2

defaults: &defaults
  working_directory: ~/apto-ui
  docker:
    - image: circleci/node:8-browsers

jobs:
  continuous-integration:
    <<: *defaults
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn install
      - run: yarn lint
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ~/apto-ui
          paths: .
      - run: yarn test:headless

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/apto-ui
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: yarn global add gulp-cli
      - run: yarn packagr
      - run: npm publish dist
      - run: npm run deploy-storybook -- --ci --host-token-env-variable=GITHUB_ACCESS_TOKEN

workflows:
  version: 2
  branches:
    jobs:
      - continuous-integration:
          filters:
            branches:
              ignore: master
  master:
    jobs:
      - continuous-integration:
          filters:
            branches:
              only: master
      - deploy:
            requires:
              - continuous-integration
